// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf2z328u2KQibkr0RUK_oMOhYw_ex3Llk',
    appId: '1:47382789745:web:bae8a2181441430f8ee5d0',
    messagingSenderId: '47382789745',
    projectId: 'storageachadoseperdidos',
    authDomain: 'storageachadoseperdidos.firebaseapp.com',
    storageBucket: 'storageachadoseperdidos.appspot.com',
    measurementId: 'G-KLE9RTCYYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYR062TOe0oD9YwG_Whf05HbkQB_XqOzM',
    appId: '1:47382789745:android:48dcb9247c172af18ee5d0',
    messagingSenderId: '47382789745',
    projectId: 'storageachadoseperdidos',
    storageBucket: 'storageachadoseperdidos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMrvYto9OOptwZsUD0Jny52QwEL_aVRA',
    appId: '1:47382789745:ios:fa94a96ee535c3338ee5d0',
    messagingSenderId: '47382789745',
    projectId: 'storageachadoseperdidos',
    storageBucket: 'storageachadoseperdidos.appspot.com',
    iosBundleId: 'com.example.perdidosEAchados',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMrvYto9OOptwZsUD0Jny52QwEL_aVRA',
    appId: '1:47382789745:ios:fa94a96ee535c3338ee5d0',
    messagingSenderId: '47382789745',
    projectId: 'storageachadoseperdidos',
    storageBucket: 'storageachadoseperdidos.appspot.com',
    iosBundleId: 'com.example.perdidosEAchados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf2z328u2KQibkr0RUK_oMOhYw_ex3Llk',
    appId: '1:47382789745:web:1d9d3cf79c145ba08ee5d0',
    messagingSenderId: '47382789745',
    projectId: 'storageachadoseperdidos',
    authDomain: 'storageachadoseperdidos.firebaseapp.com',
    storageBucket: 'storageachadoseperdidos.appspot.com',
    measurementId: 'G-9NHT0DBRBX',
  );
}
